"""remigrate

Revision ID: 3ed0302acabc
Revises: 706e3bfcf563
Create Date: 2026-09-01 21:57:02.641042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ed0302acabc'
down_revision: Union[str, Sequence[str], None] = '706e3bfcf563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_search_states_id'), table_name='order_search_states')
    op.drop_index(op.f('ix_order_search_states_order_number'), table_name='order_search_states')
    op.drop_table('order_search_states')
    op.drop_index(op.f('ix_rider_offers_id'), table_name='rider_offers')
    op.drop_index(op.f('ix_rider_offers_order_number'), table_name='rider_offers')
    op.drop_table('rider_offers')
    op.drop_index(op.f('ix_apirequests_wamid'), table_name='apiRequests')
    op.add_column('orders', sa.Column('customer_intital_offered_price', sa.String(), nullable=True))
    op.drop_column('orders', 'is_priority')
    op.drop_column('orders', 'customer_initial_offered_price')
    op.drop_column('orders', 'is_drug')
    op.drop_column('orders', 'is_urgent')
    op.add_column('riders', sa.Column('availabilty_status', sa.String(length=50), server_default='offline', nullable=False))
    op.drop_column('riders', 'availability_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('riders', sa.Column('availability_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('riders', 'availabilty_status')
    op.add_column('orders', sa.Column('is_urgent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('is_drug', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('customer_initial_offered_price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('is_priority', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_column('orders', 'customer_intital_offered_price')
    op.create_index(op.f('ix_apirequests_wamid'), 'apiRequests', ['wamid'], unique=True)
    op.create_table('rider_offers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rider_wa_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('rider_offers_pkey'))
    )
    op.create_index(op.f('ix_rider_offers_order_number'), 'rider_offers', ['order_number'], unique=False)
    op.create_index(op.f('ix_rider_offers_id'), 'rider_offers', ['id'], unique=False)
    op.create_table('order_search_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('search_round', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_followup_stage', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fare_escalation_offered', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('order_search_states_pkey'))
    )
    op.create_index(op.f('ix_order_search_states_order_number'), 'order_search_states', ['order_number'], unique=True)
    op.create_index(op.f('ix_order_search_states_id'), 'order_search_states', ['id'], unique=False)
    # ### end Alembic commands ###
