"""introduced deduplication

Revision ID: 706e3bfcf563
Revises: 
Create Date: 2026-08-14 00:04:37.663246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706e3bfcf563'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apiRequests', sa.Column('wamid', sa.Text(), nullable=True))
    op.create_index(op.f('ix_apiRequests_wamid'), 'apiRequests', ['wamid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apiRequests_wamid'), table_name='apiRequests')
    op.drop_column('apiRequests', 'wamid')
    # ### end Alembic commands ###
