"""remove testnewcolumn to to orders

Revision ID: 8294c986b3ef
Revises: 3863738102a7
Create Date: 2026-08-13 20:14:58.519874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8294c986b3ef'
down_revision: Union[str, Sequence[str], None] = '3863738102a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'sender_wa_number2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sender_wa_number2', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
